//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.431
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orbita.Controles.GateSuite.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Orbita.Controles.GateSuite.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static System.Drawing.Bitmap AbrirCarril_30x30 {
            get {
                object obj = ResourceManager.GetObject("AbrirCarril_30x30", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Advertencia_256x256 {
            get {
                object obj = ResourceManager.GetObject("Advertencia_256x256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Advertencia_42x36 {
            get {
                object obj = ResourceManager.GetObject("Advertencia_42x36", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Alarmas_36x36 {
            get {
                object obj = ResourceManager.GetObject("Alarmas_36x36", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Añadir_20x20 {
            get {
                object obj = ResourceManager.GetObject("Añadir_20x20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap AñadirContenedor_16x16 {
            get {
                object obj = ResourceManager.GetObject("AñadirContenedor_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Aspa_28x28 {
            get {
                object obj = ResourceManager.GetObject("Aspa_28x28", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Aspa_61x48 {
            get {
                object obj = ResourceManager.GetObject("Aspa_61x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BarreraHorizontal_63x8 {
            get {
                object obj = ResourceManager.GetObject("BarreraHorizontal_63x8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BarreraVertical_8x108 {
            get {
                object obj = ResourceManager.GetObject("BarreraVertical_8x108", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Borrar_72x72 {
            get {
                object obj = ResourceManager.GetObject("Borrar_72x72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Boton_174x97 {
            get {
                object obj = ResourceManager.GetObject("Boton_174x97", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap CamionDerecho_100x87 {
            get {
                object obj = ResourceManager.GetObject("CamionDerecho_100x87", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap CamionIzquierdo_100x87 {
            get {
                object obj = ResourceManager.GetObject("CamionIzquierdo_100x87", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap CamionSuperior_100x87 {
            get {
                object obj = ResourceManager.GetObject("CamionSuperior_100x87", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap CamionTrasero_100x87 {
            get {
                object obj = ResourceManager.GetObject("CamionTrasero_100x87", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap CancelarAcceso_64x64 {
            get {
                object obj = ResourceManager.GetObject("CancelarAcceso_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Comunica_32x32 {
            get {
                object obj = ResourceManager.GetObject("Comunica_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Comunica_48x48 {
            get {
                object obj = ResourceManager.GetObject("Comunica_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Editar20x20 {
            get {
                object obj = ResourceManager.GetObject("Editar20x20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Eliminar_20x20 {
            get {
                object obj = ResourceManager.GetObject("Eliminar_20x20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Error_256x256 {
            get {
                object obj = ResourceManager.GetObject("Error_256x256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ErrorImpresora_30x30 {
            get {
                object obj = ResourceManager.GetObject("ErrorImpresora_30x30", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ErrorKiosco_30x30 {
            get {
                object obj = ResourceManager.GetObject("ErrorKiosco_30x30", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap España_120x80 {
            get {
                object obj = ResourceManager.GetObject("España_120x80", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Espera_100x100 {
            get {
                object obj = ResourceManager.GetObject("Espera_100x100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Espera_300x300 {
            get {
                object obj = ResourceManager.GetObject("Espera_300x300", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Flecha_28x28 {
            get {
                object obj = ResourceManager.GetObject("Flecha_28x28", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Flecha_61x48 {
            get {
                object obj = ResourceManager.GetObject("Flecha_61x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap FondoPantalla {
            get {
                object obj = ResourceManager.GetObject("FondoPantalla", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ForzarADR_42x42 {
            get {
                object obj = ResourceManager.GetObject("ForzarADR_42x42", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ForzarAlarma_64x64 {
            get {
                object obj = ResourceManager.GetObject("ForzarAlarma_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ForzarLPR_42x42 {
            get {
                object obj = ResourceManager.GetObject("ForzarLPR_42x42", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ForzarOCR_42x42 {
            get {
                object obj = ResourceManager.GetObject("ForzarOCR_42x42", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Graficos_48x48 {
            get {
                object obj = ResourceManager.GetObject("Graficos_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Impresora_250x250 {
            get {
                object obj = ResourceManager.GetObject("Impresora_250x250", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Inglaterra_120x80 {
            get {
                object obj = ResourceManager.GetObject("Inglaterra_120x80", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap NoComunica_32x32 {
            get {
                object obj = ResourceManager.GetObject("NoComunica_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap NoComunica_48x48 {
            get {
                object obj = ResourceManager.GetObject("NoComunica_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap NoHayImagen {
            get {
                object obj = ResourceManager.GetObject("NoHayImagen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap PermutarADR_16x16 {
            get {
                object obj = ResourceManager.GetObject("PermutarADR_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Precaucion_64x64 {
            get {
                object obj = ResourceManager.GetObject("Precaucion_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap PresenciaNOK_16x16 {
            get {
                object obj = ResourceManager.GetObject("PresenciaNOK_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap PresenciaOK_16x16 {
            get {
                object obj = ResourceManager.GetObject("PresenciaOK_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap QuitarContenedor_16x16 {
            get {
                object obj = ResourceManager.GetObject("QuitarContenedor_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Reescanear_30x30 {
            get {
                object obj = ResourceManager.GetObject("Reescanear_30x30", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Reprocesar_256x256 {
            get {
                object obj = ResourceManager.GetObject("Reprocesar_256x256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Reprocesar_64x64 {
            get {
                object obj = ResourceManager.GetObject("Reprocesar_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ResetCarril_42x42 {
            get {
                object obj = ResourceManager.GetObject("ResetCarril_42x42", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Salir_36x36 {
            get {
                object obj = ResourceManager.GetObject("Salir_36x36", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap SemaforoRojo_18x28 {
            get {
                object obj = ResourceManager.GetObject("SemaforoRojo_18x28", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap SemaforoVerde_19x28 {
            get {
                object obj = ResourceManager.GetObject("SemaforoVerde_19x28", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Teclado_72x72 {
            get {
                object obj = ResourceManager.GetObject("Teclado_72x72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Volver_36x36 {
            get {
                object obj = ResourceManager.GetObject("Volver_36x36", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Web_36x36 {
            get {
                object obj = ResourceManager.GetObject("Web_36x36", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
