//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.269
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orbita.VAHardware.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Orbita.VAHardware.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Axis223M {
            get {
                object obj = ResourceManager.GetObject("Axis223M", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AxisM1114 {
            get {
                object obj = ResourceManager.GetObject("AxisM1114", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnCancelar24 {
            get {
                object obj = ResourceManager.GetObject("btnCancelar24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnGuardar24 {
            get {
                object obj = ResourceManager.GetObject("btnGuardar24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CamaraConectada {
            get {
                object obj = ResourceManager.GetObject("CamaraConectada", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CamaraDesConectada {
            get {
                object obj = ResourceManager.GetObject("CamaraDesConectada", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgBeginning24 {
            get {
                object obj = ResourceManager.GetObject("imgBeginning24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgCamaraBasler {
            get {
                object obj = ResourceManager.GetObject("imgCamaraBasler", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgChat16 {
            get {
                object obj = ResourceManager.GetObject("ImgChat16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgDelete24 {
            get {
                object obj = ResourceManager.GetObject("imgDelete24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgFloppy16 {
            get {
                object obj = ResourceManager.GetObject("imgFloppy16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgFoto24 {
            get {
                object obj = ResourceManager.GetObject("imgFoto24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgFoto32 {
            get {
                object obj = ResourceManager.GetObject("imgFoto32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgFotoForzada32 {
            get {
                object obj = ResourceManager.GetObject("imgFotoForzada32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgFullScreen16 {
            get {
                object obj = ResourceManager.GetObject("imgFullScreen16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgInfo12 {
            get {
                object obj = ResourceManager.GetObject("imgInfo12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgInfo16 {
            get {
                object obj = ResourceManager.GetObject("imgInfo16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgInfo24 {
            get {
                object obj = ResourceManager.GetObject("imgInfo24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgInicio {
            get {
                object obj = ResourceManager.GetObject("imgInicio", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgLast24 {
            get {
                object obj = ResourceManager.GetObject("imgLast24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgMonitorizarVariable24 {
            get {
                object obj = ResourceManager.GetObject("imgMonitorizarVariable24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgNew24 {
            get {
                object obj = ResourceManager.GetObject("imgNew24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgNext24 {
            get {
                object obj = ResourceManager.GetObject("imgNext24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgNextDoc16 {
            get {
                object obj = ResourceManager.GetObject("ImgNextDoc16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgNoFullScreen16 {
            get {
                object obj = ResourceManager.GetObject("imgNoFullScreen16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgPrev24 {
            get {
                object obj = ResourceManager.GetObject("imgPrev24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgPrevDoc16 {
            get {
                object obj = ResourceManager.GetObject("ImgPrevDoc16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgVariableActiva24 {
            get {
                object obj = ResourceManager.GetObject("imgVariableActiva24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgVariableActiva32 {
            get {
                object obj = ResourceManager.GetObject("imgVariableActiva32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgVariableInactiva24 {
            get {
                object obj = ResourceManager.GetObject("imgVariableInactiva24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgVariableInactiva32 {
            get {
                object obj = ResourceManager.GetObject("imgVariableInactiva32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgVistasVariables24 {
            get {
                object obj = ResourceManager.GetObject("imgVistasVariables24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a VISION_PRO;MEASUREMENT_COMPUTING;AXIS_CAMARA;SCED_IO.
        /// </summary>
        internal static string PARAMETROS_COMPILACION {
            get {
                return ResourceManager.GetString("PARAMETROS_COMPILACION", resourceCulture);
            }
        }
    }
}
