//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.296
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orbita.Controles.Estilos.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Orbita.Controles.Estilos.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] _1 {
            get {
                object obj = ResourceManager.GetObject("_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] _3 {
            get {
                object obj = ResourceManager.GetObject("_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Aero {
            get {
                object obj = ResourceManager.GetObject("Aero", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] AppStyle {
            get {
                object obj = ResourceManager.GetObject("AppStyle", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] BlackStyleSet {
            get {
                object obj = ResourceManager.GetObject("BlackStyleSet", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Claymation {
            get {
                object obj = ResourceManager.GetObject("Claymation", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Exported_Resources {
            get {
                object obj = ResourceManager.GetObject("Exported_Resources", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] FlatNature {
            get {
                object obj = ResourceManager.GetObject("FlatNature", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] IG {
            get {
                object obj = ResourceManager.GetObject("IG", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] LucidDream {
            get {
                object obj = ResourceManager.GetObject("LucidDream", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ModClay {
            get {
                object obj = ResourceManager.GetObject("ModClay", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Nautilus {
            get {
                object obj = ResourceManager.GetObject("Nautilus", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] NoirModerne {
            get {
                object obj = ResourceManager.GetObject("NoirModerne", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] None {
            get {
                object obj = ResourceManager.GetObject("None", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Ocean_blue3_pill {
            get {
                object obj = ResourceManager.GetObject("Ocean_blue3_pill", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Office2010Black {
            get {
                object obj = ResourceManager.GetObject("Office2010Black", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Office2010Blue {
            get {
                object obj = ResourceManager.GetObject("Office2010Blue", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Office2010Blue2 {
            get {
                object obj = ResourceManager.GetObject("Office2010Blue2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Office2010Silver {
            get {
                object obj = ResourceManager.GetObject("Office2010Silver", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Orbita {
            get {
                object obj = ResourceManager.GetObject("Orbita", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Orbita1 {
            get {
                object obj = ResourceManager.GetObject("Orbita1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Orbita2 {
            get {
                object obj = ResourceManager.GetObject("Orbita2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Orbita3 {
            get {
                object obj = ResourceManager.GetObject("Orbita3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Orbita4 {
            get {
                object obj = ResourceManager.GetObject("Orbita4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Orbita5 {
            get {
                object obj = ResourceManager.GetObject("Orbita5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Orbita6 {
            get {
                object obj = ResourceManager.GetObject("Orbita6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Orbita7 {
            get {
                object obj = ResourceManager.GetObject("Orbita7", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] RubberBlack {
            get {
                object obj = ResourceManager.GetObject("RubberBlack", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Template_Cherry {
            get {
                object obj = ResourceManager.GetObject("Template_Cherry", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Template_Glassy {
            get {
                object obj = ResourceManager.GetObject("Template_Glassy", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Template_GrapeTomato {
            get {
                object obj = ResourceManager.GetObject("Template_GrapeTomato", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Template_LucidDream {
            get {
                object obj = ResourceManager.GetObject("Template_LucidDream", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Template_Nautilus {
            get {
                object obj = ResourceManager.GetObject("Template_Nautilus", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Template_Office2007 {
            get {
                object obj = ResourceManager.GetObject("Template_Office2007", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] TheBlues {
            get {
                object obj = ResourceManager.GetObject("TheBlues", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Trendy {
            get {
                object obj = ResourceManager.GetObject("Trendy", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] VS2008 {
            get {
                object obj = ResourceManager.GetObject("VS2008", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] VS2010 {
            get {
                object obj = ResourceManager.GetObject("VS2010", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] VS20100 {
            get {
                object obj = ResourceManager.GetObject("VS20100", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
