//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.269
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orbita.Controles.VA.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Orbita.Controles.VA.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap btnAncla24 {
            get {
                object obj = ResourceManager.GetObject("btnAncla24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnEstablecerEscritorio16 {
            get {
                object obj = ResourceManager.GetObject("btnEstablecerEscritorio16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BtnNok24 {
            get {
                object obj = ResourceManager.GetObject("BtnNok24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnOk24 {
            get {
                object obj = ResourceManager.GetObject("btnOk24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BtnToolTips24 {
            get {
                object obj = ResourceManager.GetObject("BtnToolTips24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CamaraConectada {
            get {
                object obj = ResourceManager.GetObject("CamaraConectada", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CamaraDesConectada {
            get {
                object obj = ResourceManager.GetObject("CamaraDesConectada", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon icono {
            get {
                object obj = ResourceManager.GetObject("icono", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgChat16 {
            get {
                object obj = ResourceManager.GetObject("ImgChat16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgContadorActivo24 {
            get {
                object obj = ResourceManager.GetObject("imgContadorActivo24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgContadorActivo32 {
            get {
                object obj = ResourceManager.GetObject("imgContadorActivo32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgContadorInactivo24 {
            get {
                object obj = ResourceManager.GetObject("imgContadorInactivo24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgContadorInactivo32 {
            get {
                object obj = ResourceManager.GetObject("imgContadorInactivo32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgDesktop48 {
            get {
                object obj = ResourceManager.GetObject("imgDesktop48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgError64 {
            get {
                object obj = ResourceManager.GetObject("imgError64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgEscenariosVariables {
            get {
                object obj = ResourceManager.GetObject("ImgEscenariosVariables", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgFloppy16 {
            get {
                object obj = ResourceManager.GetObject("imgFloppy16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgFoto24 {
            get {
                object obj = ResourceManager.GetObject("imgFoto24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgFoto32 {
            get {
                object obj = ResourceManager.GetObject("imgFoto32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgFotoForzada24 {
            get {
                object obj = ResourceManager.GetObject("imgFotoForzada24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgFotoForzada32 {
            get {
                object obj = ResourceManager.GetObject("imgFotoForzada32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgFullScreen16 {
            get {
                object obj = ResourceManager.GetObject("imgFullScreen16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgHand16 {
            get {
                object obj = ResourceManager.GetObject("ImgHand16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgInfo16 {
            get {
                object obj = ResourceManager.GetObject("imgInfo16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgInfo24 {
            get {
                object obj = ResourceManager.GetObject("ImgInfo24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgLogo {
            get {
                object obj = ResourceManager.GetObject("imgLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgMonitorizarVariable24 {
            get {
                object obj = ResourceManager.GetObject("imgMonitorizarVariable24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgNextDoc16 {
            get {
                object obj = ResourceManager.GetObject("ImgNextDoc16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgNoFullScreen16 {
            get {
                object obj = ResourceManager.GetObject("imgNoFullScreen16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgNuevaTransicion24 {
            get {
                object obj = ResourceManager.GetObject("ImgNuevaTransicion24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgNuevoEstado24 {
            get {
                object obj = ResourceManager.GetObject("ImgNuevoEstado24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgNumero24 {
            get {
                object obj = ResourceManager.GetObject("imgNumero24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgNumero32 {
            get {
                object obj = ResourceManager.GetObject("imgNumero32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgNumeroForzada24 {
            get {
                object obj = ResourceManager.GetObject("imgNumeroForzada24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgNumeroForzada32 {
            get {
                object obj = ResourceManager.GetObject("imgNumeroForzada32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgPlay16 {
            get {
                object obj = ResourceManager.GetObject("ImgPlay16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgPointer16 {
            get {
                object obj = ResourceManager.GetObject("ImgPointer16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgPosicion16 {
            get {
                object obj = ResourceManager.GetObject("ImgPosicion16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgPrev24 {
            get {
                object obj = ResourceManager.GetObject("imgPrev24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgPrevDoc16 {
            get {
                object obj = ResourceManager.GetObject("ImgPrevDoc16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgQuickBuild24 {
            get {
                object obj = ResourceManager.GetObject("imgQuickBuild24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgSeleccion16 {
            get {
                object obj = ResourceManager.GetObject("ImgSeleccion16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgSnap16 {
            get {
                object obj = ResourceManager.GetObject("ImgSnap16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgStop16 {
            get {
                object obj = ResourceManager.GetObject("ImgStop16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgStop24 {
            get {
                object obj = ResourceManager.GetObject("ImgStop24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgTamaño16 {
            get {
                object obj = ResourceManager.GetObject("ImgTamaño16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgTarget16 {
            get {
                object obj = ResourceManager.GetObject("ImgTarget16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgTexto24 {
            get {
                object obj = ResourceManager.GetObject("imgTexto24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgTexto32 {
            get {
                object obj = ResourceManager.GetObject("imgTexto32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgTextoForzada24 {
            get {
                object obj = ResourceManager.GetObject("imgTextoForzada24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgTextoForzada32 {
            get {
                object obj = ResourceManager.GetObject("imgTextoForzada32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgUsuarios48 {
            get {
                object obj = ResourceManager.GetObject("ImgUsuarios48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgVariableActiva24 {
            get {
                object obj = ResourceManager.GetObject("imgVariableActiva24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgVariableActiva32 {
            get {
                object obj = ResourceManager.GetObject("imgVariableActiva32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgVariableActivaForzada24 {
            get {
                object obj = ResourceManager.GetObject("imgVariableActivaForzada24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgVariableActivaForzada32 {
            get {
                object obj = ResourceManager.GetObject("imgVariableActivaForzada32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgVariableInactiva24 {
            get {
                object obj = ResourceManager.GetObject("imgVariableInactiva24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgVariableInactiva32 {
            get {
                object obj = ResourceManager.GetObject("imgVariableInactiva32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgVariableInactivaForzada24 {
            get {
                object obj = ResourceManager.GetObject("imgVariableInactivaForzada24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgVariableInactivaForzada32 {
            get {
                object obj = ResourceManager.GetObject("imgVariableInactivaForzada32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgVistasVariables24 {
            get {
                object obj = ResourceManager.GetObject("imgVistasVariables24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgWarning24 {
            get {
                object obj = ResourceManager.GetObject("ImgWarning24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgWindows48 {
            get {
                object obj = ResourceManager.GetObject("imgWindows48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgZoom16 {
            get {
                object obj = ResourceManager.GetObject("ImgZoom16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgZoomFit16 {
            get {
                object obj = ResourceManager.GetObject("ImgZoomFit16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgZoomIn16 {
            get {
                object obj = ResourceManager.GetObject("ImgZoomIn16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgZoomOut16 {
            get {
                object obj = ResourceManager.GetObject("ImgZoomOut16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
