//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.269
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orbita.VAComun.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Orbita.VAComun.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap btnAdd16 {
            get {
                object obj = ResourceManager.GetObject("btnAdd16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnAncla24 {
            get {
                object obj = ResourceManager.GetObject("btnAncla24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnAncla48 {
            get {
                object obj = ResourceManager.GetObject("btnAncla48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnCancelar24 {
            get {
                object obj = ResourceManager.GetObject("btnCancelar24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnEliminar16 {
            get {
                object obj = ResourceManager.GetObject("btnEliminar16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnEstablecerEscritorio16 {
            get {
                object obj = ResourceManager.GetObject("btnEstablecerEscritorio16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnGuardar24 {
            get {
                object obj = ResourceManager.GetObject("btnGuardar24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnModificar16 {
            get {
                object obj = ResourceManager.GetObject("btnModificar16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BtnNok16 {
            get {
                object obj = ResourceManager.GetObject("BtnNok16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BtnNok24 {
            get {
                object obj = ResourceManager.GetObject("BtnNok24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnOk16 {
            get {
                object obj = ResourceManager.GetObject("btnOk16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnOk24 {
            get {
                object obj = ResourceManager.GetObject("btnOk24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BtnToolTips24 {
            get {
                object obj = ResourceManager.GetObject("BtnToolTips24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnVer16 {
            get {
                object obj = ResourceManager.GetObject("btnVer16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgBeginning24 {
            get {
                object obj = ResourceManager.GetObject("imgBeginning24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgChat16 {
            get {
                object obj = ResourceManager.GetObject("ImgChat16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgContadorActivo24 {
            get {
                object obj = ResourceManager.GetObject("imgContadorActivo24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgContadorActivo32 {
            get {
                object obj = ResourceManager.GetObject("imgContadorActivo32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgContadorInactivo24 {
            get {
                object obj = ResourceManager.GetObject("imgContadorInactivo24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgContadorInactivo32 {
            get {
                object obj = ResourceManager.GetObject("imgContadorInactivo32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgDelete24 {
            get {
                object obj = ResourceManager.GetObject("imgDelete24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgDesktop48 {
            get {
                object obj = ResourceManager.GetObject("imgDesktop48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgError64 {
            get {
                object obj = ResourceManager.GetObject("imgError64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgFloppy16 {
            get {
                object obj = ResourceManager.GetObject("imgFloppy16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgFullScreen16 {
            get {
                object obj = ResourceManager.GetObject("imgFullScreen16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgHand16 {
            get {
                object obj = ResourceManager.GetObject("ImgHand16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgInfo16 {
            get {
                object obj = ResourceManager.GetObject("imgInfo16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgLast24 {
            get {
                object obj = ResourceManager.GetObject("imgLast24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgLogo {
            get {
                object obj = ResourceManager.GetObject("imgLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgNew24 {
            get {
                object obj = ResourceManager.GetObject("imgNew24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgNext24 {
            get {
                object obj = ResourceManager.GetObject("imgNext24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgNextDoc16 {
            get {
                object obj = ResourceManager.GetObject("ImgNextDoc16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgNoFullScreen16 {
            get {
                object obj = ResourceManager.GetObject("imgNoFullScreen16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgPointer16 {
            get {
                object obj = ResourceManager.GetObject("ImgPointer16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgPosicion16 {
            get {
                object obj = ResourceManager.GetObject("ImgPosicion16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgPrev24 {
            get {
                object obj = ResourceManager.GetObject("imgPrev24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgPrevDoc16 {
            get {
                object obj = ResourceManager.GetObject("ImgPrevDoc16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgSeleccion16 {
            get {
                object obj = ResourceManager.GetObject("ImgSeleccion16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgSeleccionado16 {
            get {
                object obj = ResourceManager.GetObject("ImgSeleccionado16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgTamaño16 {
            get {
                object obj = ResourceManager.GetObject("ImgTamaño16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgTarget16 {
            get {
                object obj = ResourceManager.GetObject("ImgTarget16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgUsuarios48 {
            get {
                object obj = ResourceManager.GetObject("ImgUsuarios48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgWindows48 {
            get {
                object obj = ResourceManager.GetObject("imgWindows48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgZona16 {
            get {
                object obj = ResourceManager.GetObject("ImgZona16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgZoom16 {
            get {
                object obj = ResourceManager.GetObject("ImgZoom16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgZoomFit16 {
            get {
                object obj = ResourceManager.GetObject("ImgZoomFit16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgZoomIn16 {
            get {
                object obj = ResourceManager.GetObject("ImgZoomIn16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgZoomOut16 {
            get {
                object obj = ResourceManager.GetObject("ImgZoomOut16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NOHASP;NOVISION_PRO;NOLPR;NOOCR_CONTAINER;NOCHILLKAT.
        /// </summary>
        internal static string PARAMETROS_COMPILACION {
            get {
                return ResourceManager.GetString("PARAMETROS_COMPILACION", resourceCulture);
            }
        }
    }
}
