//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.1
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orbita.VAControl.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Orbita.VAControl.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap btnAdd16 {
            get {
                object obj = ResourceManager.GetObject("btnAdd16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnCancelar24 {
            get {
                object obj = ResourceManager.GetObject("btnCancelar24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnEliminar16 {
            get {
                object obj = ResourceManager.GetObject("btnEliminar16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnGuardar24 {
            get {
                object obj = ResourceManager.GetObject("btnGuardar24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnModificar16 {
            get {
                object obj = ResourceManager.GetObject("btnModificar16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnVer16 {
            get {
                object obj = ResourceManager.GetObject("btnVer16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgBeginning24 {
            get {
                object obj = ResourceManager.GetObject("imgBeginning24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgDelete24 {
            get {
                object obj = ResourceManager.GetObject("imgDelete24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgEscenariosVariables {
            get {
                object obj = ResourceManager.GetObject("ImgEscenariosVariables", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgEstado16 {
            get {
                object obj = ResourceManager.GetObject("imgEstado16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgEstado24 {
            get {
                object obj = ResourceManager.GetObject("imgEstado24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgFoto24 {
            get {
                object obj = ResourceManager.GetObject("imgFoto24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgFoto32 {
            get {
                object obj = ResourceManager.GetObject("imgFoto32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgFotoForzada24 {
            get {
                object obj = ResourceManager.GetObject("imgFotoForzada24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgFotoForzada32 {
            get {
                object obj = ResourceManager.GetObject("imgFotoForzada32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgInfo24 {
            get {
                object obj = ResourceManager.GetObject("ImgInfo24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgLast24 {
            get {
                object obj = ResourceManager.GetObject("imgLast24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgMonitorizarVariable24 {
            get {
                object obj = ResourceManager.GetObject("imgMonitorizarVariable24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgNew24 {
            get {
                object obj = ResourceManager.GetObject("imgNew24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgNext24 {
            get {
                object obj = ResourceManager.GetObject("imgNext24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgNuevaTransicion24 {
            get {
                object obj = ResourceManager.GetObject("ImgNuevaTransicion24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgNuevoEstado24 {
            get {
                object obj = ResourceManager.GetObject("ImgNuevoEstado24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgNumero24 {
            get {
                object obj = ResourceManager.GetObject("imgNumero24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgNumero32 {
            get {
                object obj = ResourceManager.GetObject("imgNumero32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgNumeroForzada24 {
            get {
                object obj = ResourceManager.GetObject("imgNumeroForzada24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgNumeroForzada32 {
            get {
                object obj = ResourceManager.GetObject("imgNumeroForzada32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgPrev24 {
            get {
                object obj = ResourceManager.GetObject("imgPrev24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgStop24 {
            get {
                object obj = ResourceManager.GetObject("ImgStop24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgTexto24 {
            get {
                object obj = ResourceManager.GetObject("imgTexto24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgTexto32 {
            get {
                object obj = ResourceManager.GetObject("imgTexto32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgTextoForzada24 {
            get {
                object obj = ResourceManager.GetObject("imgTextoForzada24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgTextoForzada32 {
            get {
                object obj = ResourceManager.GetObject("imgTextoForzada32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgTransicion16 {
            get {
                object obj = ResourceManager.GetObject("imgTransicion16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgTransicion24 {
            get {
                object obj = ResourceManager.GetObject("imgTransicion24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgVariableActiva24 {
            get {
                object obj = ResourceManager.GetObject("imgVariableActiva24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgVariableActiva32 {
            get {
                object obj = ResourceManager.GetObject("imgVariableActiva32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgVariableActivaForzada24 {
            get {
                object obj = ResourceManager.GetObject("imgVariableActivaForzada24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgVariableActivaForzada32 {
            get {
                object obj = ResourceManager.GetObject("imgVariableActivaForzada32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgVariableInactiva24 {
            get {
                object obj = ResourceManager.GetObject("imgVariableInactiva24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgVariableInactiva32 {
            get {
                object obj = ResourceManager.GetObject("imgVariableInactiva32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgVariableInactivaForzada24 {
            get {
                object obj = ResourceManager.GetObject("imgVariableInactivaForzada24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgVariableInactivaForzada32 {
            get {
                object obj = ResourceManager.GetObject("imgVariableInactivaForzada32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgVistasVariables24 {
            get {
                object obj = ResourceManager.GetObject("imgVistasVariables24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgWarning24 {
            get {
                object obj = ResourceManager.GetObject("ImgWarning24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
