<?xml version="1.0" encoding="utf-8"?>
<styleLibrary office2007CustomBlendColor="" office2010CustomBlendColor="">
  <annotation>
    <lastModified>2012-11-28T18:22:13</lastModified>
  </annotation>
  <styleSets defaultStyleSet="Default">
    <styleSet name="Default">
      <componentStyles>
        <componentStyle name="Inbox MonthCalendar">
          <properties>
            <property name="TitleBackColor" colorCategory="{Default}">224, 224, 224</property>
            <property name="TitleForeColor" colorCategory="{Default}">64, 64, 64</property>
          </properties>
        </componentStyle>
        <componentStyle name="UltraCalculator" useFlatMode="True" />
        <componentStyle name="UltraCombo" useFlatMode="True" />
        <componentStyle name="UltraDockManager" useFlatMode="True" />
        <componentStyle name="UltraDropDownButton" useFlatMode="True" />
        <componentStyle name="UltraExplorerBar" useFlatMode="True" />
        <componentStyle name="UltraOptionSet">
          <radioButtonGlyphInfo>Office2007RadioButtonGlyphInfo</radioButtonGlyphInfo>
        </componentStyle>
        <componentStyle name="UltraTree" useFlatMode="True" />
      </componentStyles>
      <styles>
        <style role="Base">
          <states>
            <state name="Normal" fontName="" textHAlign="Left" textVAlign="Middle" textTrimming="EllipsisCharacter" />
          </states>
        </style>
        <style role="DesktopAlertCaptionLink">
          <states>
            <state name="HotTracked" foreColor="Black" />
          </states>
        </style>
        <style role="DesktopAlertFooterTextLink">
          <states>
            <state name="HotTracked" foreColor="Black" fontName="Segoe UI" />
          </states>
        </style>
        <style role="DesktopAlertTextLink">
          <states>
            <state name="HotTracked" foreColor="Black" />
          </states>
        </style>
        <style role="DotNetMonthDropDownTitle">
          <states>
            <state name="Normal" backColor="224, 224, 224" foreColor="64, 64, 64" backGradientStyle="None" backHatchStyle="None" />
          </states>
        </style>
        <style role="EmptyTileArea">
          <states>
            <state name="Normal" backColor="225, 225, 225" backGradientStyle="None" backHatchStyle="None" />
          </states>
        </style>
        <style role="ExplorerBarGroupHeader">
          <states>
            <state name="Normal" borderColor="Transparent" />
          </states>
        </style>
        <style role="GridCell">
          <states>
            <state name="Active" backColor="255, 232, 166" backGradientStyle="None" backHatchStyle="None" />
            <state name="EditMode">
              <resources>
                <name>GridCellEditMode</name>
              </resources>
            </state>
          </states>
        </style>
        <style role="GridCellProxy">
          <states>
            <state name="Normal" backColor="232, 234, 236" borderColor="169, 177, 184" backGradientStyle="None" backHatchStyle="None" />
            <state name="HotTracked" backColor="White" backGradientStyle="None" backHatchStyle="None" />
          </states>
        </style>
        <style role="GridColumnHeader">
          <states>
            <state name="Normal">
              <resources>
                <name>GridColumnHeaderNormal</name>
              </resources>
            </state>
            <state name="HotTracked">
              <resources>
                <name>GridColumnHeaderHotTracked</name>
              </resources>
            </state>
          </states>
        </style>
        <style role="GridRow">
          <states>
            <state name="Normal" borderColor="195, 195, 195" />
            <state name="Active">
              <resources>
                <name>GridRowActive</name>
              </resources>
            </state>
            <state name="FilterRow" borderColor="195, 195, 195">
              <resources>
                <name>GridRowFilterRow</name>
              </resources>
            </state>
          </states>
        </style>
        <style role="GridRowEditTemplatePanel">
          <states>
            <state name="Normal" backColor="White" backGradientStyle="None" backHatchStyle="None" />
          </states>
        </style>
        <style role="GridSummaryFooter">
          <states>
            <state name="Normal" backColor="215, 215, 215" backGradientStyle="None" backHatchStyle="None" />
          </states>
        </style>
        <style role="Row">
          <states>
            <state name="AlternateItem">
              <resources>
                <name>GridRowAlternateItem</name>
              </resources>
            </state>
          </states>
        </style>
        <style role="ScheduleOwner">
          <states>
            <state name="Normal" backColor="150, 150, 150" backGradientStyle="None" backHatchStyle="None" />
          </states>
        </style>
        <style role="TabCloseButton">
          <states>
            <state name="Normal" backColor="Transparent" imageBackgroundStyle="Centered" foregroundAlpha="Transparent" borderAlpha="Transparent" backGradientStyle="None" backHatchStyle="None">
              <imageBackground>AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAADQEAAAKJUE5HDQoaCgAAAA1JSERSAAAAEQAAABEIBgAAADttR/oAAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsMAAALDAE/QCLIAAAAdklEQVQ4T2P4//8/A6WYYgNADhjuhqSmpv6HYeQAxyWOM0zyy+r+wzBIETofPTZxBmxl2/T/6BhXUsAbO7U9C/7DML60hNeQ+v7F/2GYLEOaJi3/j45J8k7L1FX/YRikEZ1PMGDbZ6z7D8PIinGJj4RkT07ZAgD6d0+KuyhQiwAAAABJRU5ErkJgggsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=</imageBackground>
            </state>
            <state name="HotTracked" imageBackgroundStyle="Centered" foregroundAlpha="Transparent">
              <imageBackground>AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAAIgIAAAKJUE5HDQoaCgAAAA1JSERSAAAAEQAAABEIBgAAADttR/oAAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsMAAALDAE/QCLIAAABi0lEQVQ4T52UPUvDUBSG+0/aP9fZTXBQQUQXQRBER8FBcFA3N+MiuLSIFAcHwbZqaz9scm++mqTH896b3KStInF4aM+5533ObSCt3DdaNeaKoX+AXK1yc/dgPT23KZlRaZBDvnJ926SEDWMnoC/h00QGZMuQHC8k4U1J+jmo0cc55pBDXkliJfG1RARqQEvCBYmW4xxzyOWSeEYjlmgRJLzNZZGrRbgBPlGjj3PMxZwzkoiLoe0pUb1eN9j4aSoYzvUhwELkCpKEJT6NUtHK6gZl4NrFWgsCtTCKk1wyjRIaTDyFuhEL13aOlhjzM0MY55hDztzEcafU/RT0NhD0PpT0wfRGLq3vnRj6Y5cA+jjHHHJaYjVU0e471OmLVCZZKGlz/9SAEEAfYKmScF5J8PQhyUQdHtg6OFuim4ZxjoXI/SiBaPvw3IDAXM3hTrpwQRLRa89R7B5fGLLeb33hRcWb5JJi8K/vcxLpQ2KXBrnsmVjN1gu/I1FpkGOJxX8Fj1XmkuHXujTIVb8Bbt355gHAqXoAAAAASUVORK5CYIILAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==</imageBackground>
            </state>
            <state name="Pressed" imageBackgroundStyle="Centered" foregroundAlpha="Transparent">
              <imageBackground>AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAASQIAAAKJUE5HDQoaCgAAAA1JSERSAAAAEQAAABEIBgAAADttR/oAAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsMAAALDAE/QCLIAAABsklEQVQ4T52TyUrDUBSG75vUl+vaneBCBRHdCIIDDjgPVKvW2mhbO5jSKbGJSZtWW4ciiEpB8BV+7x/ohSou4uJLOOf838lExMLKxpAkLsE/oDck5EHXUln0Pr8CQ48+l+D1vYd6sxMYevT9Jc8vr7DdVmDoqSXtxy5Mqx4YempJo9VG2bB9wuGwot/7q09PLbFdD4WSqRgeGUcf9n/W/Sw9tcS0XOT0sk++UIFeNDA6vfwL9jnvZ+mpJYfHZziIxnEU03ASTyKWSCN+kcHY7LaCNfucM8c8PX/J4uomzrUUTs6TvqilcrjM6EhmC5iY21OwZp9z5pinR18sr+/gKqsjQVkG09dFZOUtT85HfsE+58wxT4++WNvaR14vIZkvIiNDefkip5aiitKNM1Bzzhzz9OiLjd0IimUDOfnS9EoNMysxheF4MJymxBvoM8c8Pfpi+yCKqmmjULVQqrmo3now3TvUGm1YXgeW/B14Zs0+58wxT4++2I2cwqk3/QGvWmvcw249wLl/gtPuwu10/TNr9jlnjnl69IX8VHpOPuPbRy8w9OiLw1MtJDmT4B/QC30DRBKLNrwkm/0AAAAASUVORK5CYIILAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==</imageBackground>
            </state>
          </states>
        </style>
        <style role="TabControlTabCloseButton">
          <states>
            <state name="Normal" backColor="Transparent" imageBackgroundStyle="Centered" borderAlpha="Transparent" backGradientStyle="None" backHatchStyle="None">
              <imageBackground>AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAADQEAAAKJUE5HDQoaCgAAAA1JSERSAAAAEQAAABEIBgAAADttR/oAAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsMAAALDAE/QCLIAAAAdklEQVQ4T2P4//8/A6WYYgNADhjuhqSmpv6HYeQAxyWOM0zyy+r+wzBIETofPTZxBmxl2/T/6BhXUsAbO7U9C/7DML60hNeQ+v7F/2GYLEOaJi3/j45J8k7L1FX/YRikEZ1PMGDbZ6z7D8PIinGJj4RkT07ZAgD6d0+KuyhQiwAAAABJRU5ErkJgggsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=</imageBackground>
            </state>
            <state name="HotTracked" imageBackgroundStyle="Centered" borderAlpha="Transparent">
              <imageBackground>AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAAIgIAAAKJUE5HDQoaCgAAAA1JSERSAAAAEQAAABEIBgAAADttR/oAAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsMAAALDAE/QCLIAAABi0lEQVQ4T52UPUvDUBSG+0/aP9fZTXBQQUQXQRBER8FBcFA3N+MiuLSIFAcHwbZqaz9scm++mqTH896b3KStInF4aM+5533ObSCt3DdaNeaKoX+AXK1yc/dgPT23KZlRaZBDvnJ926SEDWMnoC/h00QGZMuQHC8k4U1J+jmo0cc55pBDXkliJfG1RARqQEvCBYmW4xxzyOWSeEYjlmgRJLzNZZGrRbgBPlGjj3PMxZwzkoiLoe0pUb1eN9j4aSoYzvUhwELkCpKEJT6NUtHK6gZl4NrFWgsCtTCKk1wyjRIaTDyFuhEL13aOlhjzM0MY55hDztzEcafU/RT0NhD0PpT0wfRGLq3vnRj6Y5cA+jjHHHJaYjVU0e471OmLVCZZKGlz/9SAEEAfYKmScF5J8PQhyUQdHtg6OFuim4ZxjoXI/SiBaPvw3IDAXM3hTrpwQRLRa89R7B5fGLLeb33hRcWb5JJi8K/vcxLpQ2KXBrnsmVjN1gu/I1FpkGOJxX8Fj1XmkuHXujTIVb8Bbt355gHAqXoAAAAASUVORK5CYIILAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==</imageBackground>
            </state>
            <state name="Pressed" imageBackgroundStyle="Centered" borderAlpha="Transparent">
              <imageBackground>AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAASQIAAAKJUE5HDQoaCgAAAA1JSERSAAAAEQAAABEIBgAAADttR/oAAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsMAAALDAE/QCLIAAABsklEQVQ4T52TyUrDUBSG75vUl+vaneBCBRHdCIIDDjgPVKvW2mhbO5jSKbGJSZtWW4ciiEpB8BV+7x/ohSou4uJLOOf838lExMLKxpAkLsE/oDck5EHXUln0Pr8CQ48+l+D1vYd6sxMYevT9Jc8vr7DdVmDoqSXtxy5Mqx4YempJo9VG2bB9wuGwot/7q09PLbFdD4WSqRgeGUcf9n/W/Sw9tcS0XOT0sk++UIFeNDA6vfwL9jnvZ+mpJYfHZziIxnEU03ASTyKWSCN+kcHY7LaCNfucM8c8PX/J4uomzrUUTs6TvqilcrjM6EhmC5iY21OwZp9z5pinR18sr+/gKqsjQVkG09dFZOUtT85HfsE+58wxT4++WNvaR14vIZkvIiNDefkip5aiitKNM1Bzzhzz9OiLjd0IimUDOfnS9EoNMysxheF4MJymxBvoM8c8Pfpi+yCKqmmjULVQqrmo3now3TvUGm1YXgeW/B14Zs0+58wxT4++2I2cwqk3/QGvWmvcw249wLl/gtPuwu10/TNr9jlnjnl69IX8VHpOPuPbRy8w9OiLw1MtJDmT4B/QC30DRBKLNrwkm/0AAAAASUVORK5CYIILAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==</imageBackground>
            </state>
          </states>
        </style>
        <style role="TileCloseButton">
          <states>
            <state name="Normal">
              <imageBackground>AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAAwAAAAAKJUE5HDQoaCgAAAA1JSERSAAAAFAAAABQIBgAAAI2JHQ0AAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsMAAALDAE/QCLIAAAAKUlEQVQ4T2P4//8/AzUxVQ0DOWzUQMojaDQMR8OQjHw+mmxGkw0ZyQYAROOrjRU8tTgAAAAASUVORK5CYIILAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=</imageBackground>
            </state>
            <state name="HotTracked">
              <image>AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAA2QAAAAKJUE5HDQoaCgAAAA1JSERSAAAAEQAAAA0IBgAAAE95hRoAAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsMAAALDAE/QCLIAAAAQklEQVQ4T2P4//8/A6WYYgNADhjkhhgbG/+HYZBz0fnoYYjTO8gakQ3EFgl4w4SQC2AG0tYQir1DtYAlJRUPnsQGAB8dbXy89yqtAAAAAElFTkSuQmCCCwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=</image>
            </state>
          </states>
        </style>
        <style role="TileHeader">
          <states>
            <state name="Normal" foreColor="White" imageBackgroundStyle="Stretched" imageBackgroundStretchMargins="130, 2, 2, 2">
              <imageBackground>AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAAUA4AAAKJUE5HDQoaCgAAAA1JSERSAAABLQAAABcIBgAAAF51GZEAAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsMAAALDAE/QCLIAAANuUlEQVR4Xu2cZ3OV1xWF78/Kh2Qm3ePEGTsJEycmHjI4duw4NsE2HQmh3juSUEMS6gIkJESREF10id47iI4ootedvfYp73nvvQRiOzYJ58Oa2DME0NG5j9daex9FVvUP0MKmFmpqbaeWtg5q61hMHUs6aUlXN3V2L6OlPb20bPlKWr6yj1b2raa+1QO0es06Wrt+A63fsIk2bBqkwc1bacu27bRtx07asXOIhnbtpt179tLefftp34GDdPDQYTpy9CgdPXacjp84SadOnaYzZ8/RuZERGjl/gS5eukRXrlylq9eu0ej163Tz5k0au32b7ty5Q/fu3aMHDx7S48eP6cnTp/Ts2TOrp/zv0JMnT+gxxL/m0aNHoocPH8r/78GDB3T//n26B/HvdfcudFd+79sQ/zljY7fp1tgY3bo1Rjdv3aIb/OffuHGTrt+4IX+f0dHrdG10lK5dG5W/45WrLP77Xr5yhS5dhi7z18C6eIkuXLxI5y9AF+RrGxk5z1/neTp7boTO8teMr/vMmbN0+swZOnUaOk0n+TxOnDwlwvkcO35ChPM6chQ6RoePHKNDR47SocNH6CDEZ3rg4CHaD/EZ79sPHeAzP0B7+Nz37N3H3wNoL+3avZeGd++hYf6+DA3vpp3Du2jn0C7aMTTM369h2r5jSL5327bvpK3bdsj3csvW7bR56zYa3MLi7+8m1sbBLazN/D2HBmn9xkFax3dg3YaNfB820pp1G0QDa9fTAN8R3JP+gbWivtVrRLhvXv4MvskdiKxY1U+l5fNZlTSvopLKKqqobD5UTeWVRjVUXlVDFVB1Lc3XqqxeQJU1UB1V1SpVL6gPVNdANVq19QsJWgA1NIrqFjaJ6hubrRr4nxsYotDC5lZqNGrhf25pY7hC7dQMMWQhwLalvYNa2xeJAN62RdASUftiqJM6IAZyx5IuWgR1dtHizqVWS5Z2k1IPdULd0DLq6lECwKHuZdByUU8va/kKAbtohVLvilUMeqhPtGKVVl+/wH9l/2r+8EJ8gfk/BBA+1P3QALSWP/Raa9cxCKD1DAWltQwH/IcD6uU/p7qunjJy8rz8Gfxf3wHwKtLLH7SSeRVUUjZfVAoZiDHIQhCLAplArIohBrkgY5hZiNUyxCCBmQOxOoYYJCBjiLHqNMjqAbKFCmQCsUYNMQZZY5MLMgYYQNaiIdbqQExgtohhxhBrZ4ABZBpm7QAZSyAm0hCzMFMgg9sUMcg6RYAZAwwg0y5UICYgcyDW60BMwwwQUyDTEAPIBGaAmALZKshxInC1AjEBmQMxhlkf/zp8bflFpZSSnuXlz+C1uAPgVQROoai0nIqheeUWYC68xIXFc2KAGKuCHRkAJvCyAGMHZp1YLMRqGGKQgMvCSwPMOLEGwAtOTLmxaICFnFhzm3JirGYDsTYVeQ28Qk5MIKadGABmIMZOTFyYOLHAhRmIdSI2ayfWxU4MMg4scGIKYMqJMcCM+MB7xYVpJ+ZCDPAyYogpF6YgBkCZeIXfC044NSObklLSvfwZvFZ3ALyKdLFLKCwpo8LSMoGXEQBWzA4MCjswdmIcI+dxjIRMlAziJEfJShUnQxCTGKmiZBAngyhZAxfGqq2H4MCU+zJRcgEDTMVJdmDxXBjHSAUxBS8jREkVJ6NcmI6SrR0mTiqASZxcZBxYOEpaiDG4FlsXpqMkgyzagS3lGAkZgHUzcARiJkpaiLELM1GSY+RyhhccmAhRkoW4nFNQTLOTUrz8Gby2dwC8iiD+IGLkF5dSQfE8UWEJ6wUQs3HSiZLSiek+LF4n5kKskuPkv4OYRElAjDuxkBPTLiyAWBAllRsLoqR1YroPU07s60As6MSsC9NuTDqxLiUVJeNAzETJ50CsJx7E2IXh98I5A1TTZ8/x8mfw2t8BfMYi+BDmFZaI8osghhcUDTF2Y0UQw8xESXFh4sQqVBcW04cFEEOMNMV+BTsxKAZi6MLYjUHVKPVtF6aiZFyIsSurs31Yo4qTL+rDGGKqC3P7MFXsqziJYl+V+rbY5zjZzuV+dB9mILaYz1EkXZhRECURKa0T0xCTLkz3YT2m1Gf7C0eZlplNU6bP8vJn4O+AcwfweYtgypaTX6RUUES5HEHyoEKWhljgxJQbEyfmQExAFoqTTrGvnVhoOqljpTudFJCZYt9OKE2kBMj0dNKZUEqklOmkM5k0xb6U+mpCaSBmezEznXRLfURLAzKeUMZMJ7nUj+nEHIgF08muYDqpIWYmlDGlvplOMsQwJMA5wlH986tpXv4M/B2IcwfAqwgcRXZeAauQsvMLQ/ACwARiAJjrxBwXVqABJhBzIqWCmCn22YkJvPRqhS71g04svGJhnVg1u7GY9QrViyknFrixGh75A2AmStqppI2TmE7qYt91Yk1qxQJRMoiTxoXpYl/WK0ypr1yYdWJmKilOTE0l7WRSSn1d7LMDCxX7uhNDRE5Oy6TPJn/l5c/A34EX3AF87iIoqTNzC0RZLAswAzF2XyiABWAMr1wdJSVSoguLipICMYaX7cQYXEWOCyvmKCnFfjyIOX1YmbMjphyYjpOAWI3pw3SxLzti9VTl7IjZ/TDtwgRiDWZHrIkWxN0RU31YQ7MDsbilfmyUFIhxqd8qaxVuqe/uiKmpJH4Nzmny1Bn0yeeTvfwZ+DvwkncAvIpgGz4jm5cSRfmUmQMFEAPIsgAwLRMlc3WUVE5MdWIGYhInBWam2GeIWSemppRmMhmaTgrMgvWKmOmk9GJqOhnbiTlRshYrFgwxZ0fMTiddiDmLrlLsy4QyznSSy/2QE7NRkkt9p9i3fRj2w0ycdJwYOrw5yen04Sefefkz8Hfga9wB8CqCvictM5fSs7QswPIoExDLzWcHBsGJBfBScVJ3Yfnaidk+zBT7YXhJH8aSQl8gFuyHmU4seioZQIwjpOnCXrDkKvthekcstgtrUEuuug+LXnCVTX13W99GSXZgejIJN2Y39bFiwZJS365XBE4MsMPZfTrpC5r40d+9/Bn4O/AN7gB4FUFsSuFFRSwrpvLEKjUzRyCW5kAsnUEGBU4MMFNxMov7MOvELMRUoR90YuHpZD6DC4p1YnH2xHScFJixC3uuE7Nxkt2YLvSxra+eHbmLrhwlzbMj98mRU+rX2CdHwa6YuDC9KxZ6duQ8ObJ7YgwxuEGU6gDV+xM/8vJn4O/At3AHwKsIntckp2eqJwAZULaFGMbuaQKxHOXEsiEdJfUbL8TJwImZToz/l0t9cWLSiTkQ06V+bLHPcVJKfbcTc9crVKTEekVJuSn2GWKy6KolnViVbOkHk0ls7OtOLM5UEkW4vJmMejcpKxYo9u2yq/NmMuTE9LY+F/o40Ew+l4//MYnemzDRy5+BvwPf8h0AryL40M5NzaBkiKdYIgsx7cDEiSl4CcA0xDIYYrYPky5MSUVJU+yrSJmjpbowd7UiiJKyH+YU+2q1QsdJva3v7ogZiLk7YhZgzqJrADG3DwuK/dBzIwsx9WbS7IfZHTHz6NvpwwDIL7lU//NfPqB3x0/w8mfg78B/6Q6AVxHEGJTDc/gNF5TE8ALERNEQS1cuLIiTOTpOaiemI6WAzHFiNkrKdNIp9QGyGCdmSn216Bosu+pSX/bEzHRSPz2KN52MWnQVmGknJlv77nTSODH34bd9dmTeTepiXy+5AmI4H5Tqv3t3vJc/A38HvoM7AF5FMKFLnJtKiclpDC9WCqQf4jK4FMQy5QMaQMz8VAG3CwuipOnDgqkkSn0WnJgt9cNTSVPqh6aSzmTSbOu7z43MjpjZ1A8X+/xuUvowxEk1lXxeH+ZGSfsjeDTA3FIflMfAYPKU6TTuT+/T2+P+6OXPwN+B7/AOgFcRfKjNI9yEpFRKAMBciAnMDMQcJxYXYllOoR8LsaDQdyDmxklZco1adJVeTC+5xll0VRDTitnUd6eT0RBzQKYfgKt3k7oT072Y2RGD85zwwd/o1++M8/Jn4O/A93QHwKsItthnJc5lJdOsOck0G0qCUigBMhCbq52YdmTyY1FSXxJiejppOrG0rDjFvkRK04kFvVi2iZSyrW829l8SYs6TI7PsGnRibrHvLrvO18V+lbwEmPTlVPrtH96jN956x8ufgb8D3/MdAK8icCkzEpJoZsJcmsnwgiy8BGIaXgIwDTEGVxAndRfGELNdWEypz9NJtwuT9Qqn2LddmC72uQ/DFE7FSV3oR23rG4DZYt+ZSqrJZJyH3xpi6rmRWXLV8HIefuPrf3/ih/TzN3/j5c/A34FX6A6AVxHsUk2flciaQzN4r2hGAgSIsQzEtAszMBMH5jqxZHRiqboTCyDmlvp2MsmxMgWS9QodJ58HMYaZKfUVxFjOZBI7YsGmvnJhuZCZTgrIzLtJF2L64bcDMTxR+vyLKfSrt39PP/7Fm17+DPwdeAXvAHgVwYd+6sxE0TSIATaNAaYglmQVH2L8A+nYicV2YuzE3DjpFPvKjenVCplOMrwgvSMmS64hiAXb+hlZ5rmR3taPKfYdiOWpbf1cd1s/tCOmJpMA8/gJf6Uf/uSXXv4M/B14xe8AeCUb8VOmzxZNncGamWAVDTFseBuQCcQQKVnSiXGkCjoxBTIU+4kQA+xFEHOnkwIx+Znfzp5Y9KIrXNh/ALFsC7EicW8ffzqJfvbGW/SDH/3Uy5+BvwP/I3cAldG/AGqoigILRknJAAAAAElFTkSuQmCCCwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</imageBackground>
            </state>
          </states>
        </style>
        <style role="TileStateChangeButtonLarge">
          <states>
            <state name="Normal">
              <image>AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAA4AAAAAKJUE5HDQoaCgAAAA1JSERSAAAAEQAAAA0IBgAAAE95hRoAAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsMAAALDAE/QCLIAAAASUlEQVQ4T2P4//8/A6WYYgNADqC5IUBLcAIUy/G5hGqGYLMEZDhBlxByAcWGwCwgyiVEeQPmLVIUY3iDkCG4wgVrbNI8sRFtAQBnwMBcfuMWNQAAAABJRU5ErkJgggsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=</image>
              <imageBackground>AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAAwAAAAAKJUE5HDQoaCgAAAA1JSERSAAAAFAAAABQIBgAAAI2JHQ0AAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsMAAALDAE/QCLIAAAAKUlEQVQ4T2P4//8/AzUxVQ0DOWzUQMojaDQMR8OQjHw+mmxGkw0ZyQYAROOrjRU8tTgAAAAASUVORK5CYIILAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=</imageBackground>
            </state>
            <state name="HotTracked">
              <image>AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAA8AAAAAKJUE5HDQoaCgAAAA1JSERSAAAAEQAAAA0IBgAAAE95hRoAAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsMAAALDAE/QCLIAAAAWUlEQVQ4T2P4//8/A6WYYgNADqCtIcbGxv9NTEwwMEgc3fs4XQJSjA2DDCbaEGyKQZqJMgTmDXTvwLxBtCH4vEJUmJDiDVjYYAQsVQwhJWpxuoScLECVFAsA09NXcZHkQasAAAAASUVORK5CYIILAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=</image>
            </state>
          </states>
        </style>
        <style role="TileStateChangeButtonNormal">
          <states>
            <state name="Normal">
              <image>AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAA2AAAAAKJUE5HDQoaCgAAAA1JSERSAAAAEQAAAA0IBgAAAE95hRoAAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsMAAALDAE/QCLIAAAAQUlEQVQ4T2P4//8/A6WYYgNADhj8hgBd+f8fFgwSx3A9Lu+AFGMDIIOJNgSrYqjL6GsIVcKEpKgnSTGulD14DAEAT0etYAVWD74AAAAASUVORK5CYIILAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=</image>
            </state>
            <state name="HotTracked">
              <image>AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAA2QAAAAKJUE5HDQoaCgAAAA1JSERSAAAAEQAAAA0IBgAAAE95hRoAAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsMAAALDAE/QCLIAAAAQklEQVQ4T2P4//8/A6WYYgNADhjkhhgbG/8H4n9YMND1mGGI1TtQQ0AGoeN/pBiCVTHIZXQ3hPIwITXxDfJ0Qqp3AD1rcZwo6DNEAAAAAElFTkSuQmCCCwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=</image>
            </state>
          </states>
        </style>
        <style role="TimelineViewColumnHeaderPrimaryInterval">
          <states>
            <state name="Normal" foreColor="White" imageBackgroundStyle="Stretched" imageBackgroundStretchMargins="10, 2, 0, 0">
              <imageBackground>AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAAUA4AAAKJUE5HDQoaCgAAAA1JSERSAAABLQAAABcIBgAAAF51GZEAAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsMAAALDAE/QCLIAAANuUlEQVR4Xu2cZ3OV1xWF78/Kh2Qm3ePEGTsJEycmHjI4duw4NsE2HQmh3juSUEMS6gIkJESREF10id47iI4ootedvfYp73nvvQRiOzYJ58Oa2DME0NG5j9daex9FVvUP0MKmFmpqbaeWtg5q61hMHUs6aUlXN3V2L6OlPb20bPlKWr6yj1b2raa+1QO0es06Wrt+A63fsIk2bBqkwc1bacu27bRtx07asXOIhnbtpt179tLefftp34GDdPDQYTpy9CgdPXacjp84SadOnaYzZ8/RuZERGjl/gS5eukRXrlylq9eu0ej163Tz5k0au32b7ty5Q/fu3aMHDx7S48eP6cnTp/Ts2TOrp/zv0JMnT+gxxL/m0aNHoocPH8r/78GDB3T//n26B/HvdfcudFd+79sQ/zljY7fp1tgY3bo1Rjdv3aIb/OffuHGTrt+4IX+f0dHrdG10lK5dG5W/45WrLP77Xr5yhS5dhi7z18C6eIkuXLxI5y9AF+RrGxk5z1/neTp7boTO8teMr/vMmbN0+swZOnUaOk0n+TxOnDwlwvkcO35ChPM6chQ6RoePHKNDR47SocNH6CDEZ3rg4CHaD/EZ79sPHeAzP0B7+Nz37N3H3wNoL+3avZeGd++hYf6+DA3vpp3Du2jn0C7aMTTM369h2r5jSL5327bvpK3bdsj3csvW7bR56zYa3MLi7+8m1sbBLazN/D2HBmn9xkFax3dg3YaNfB820pp1G0QDa9fTAN8R3JP+gbWivtVrRLhvXv4MvskdiKxY1U+l5fNZlTSvopLKKqqobD5UTeWVRjVUXlVDFVB1Lc3XqqxeQJU1UB1V1SpVL6gPVNdANVq19QsJWgA1NIrqFjaJ6hubrRr4nxsYotDC5lZqNGrhf25pY7hC7dQMMWQhwLalvYNa2xeJAN62RdASUftiqJM6IAZyx5IuWgR1dtHizqVWS5Z2k1IPdULd0DLq6lECwKHuZdByUU8va/kKAbtohVLvilUMeqhPtGKVVl+/wH9l/2r+8EJ8gfk/BBA+1P3QALSWP/Raa9cxCKD1DAWltQwH/IcD6uU/p7qunjJy8rz8Gfxf3wHwKtLLH7SSeRVUUjZfVAoZiDHIQhCLAplArIohBrkgY5hZiNUyxCCBmQOxOoYYJCBjiLHqNMjqAbKFCmQCsUYNMQZZY5MLMgYYQNaiIdbqQExgtohhxhBrZ4ABZBpm7QAZSyAm0hCzMFMgg9sUMcg6RYAZAwwg0y5UICYgcyDW60BMwwwQUyDTEAPIBGaAmALZKshxInC1AjEBmQMxhlkf/zp8bflFpZSSnuXlz+C1uAPgVQROoai0nIqheeUWYC68xIXFc2KAGKuCHRkAJvCyAGMHZp1YLMRqGGKQgMvCSwPMOLEGwAtOTLmxaICFnFhzm3JirGYDsTYVeQ28Qk5MIKadGABmIMZOTFyYOLHAhRmIdSI2ayfWxU4MMg4scGIKYMqJMcCM+MB7xYVpJ+ZCDPAyYogpF6YgBkCZeIXfC044NSObklLSvfwZvFZ3ALyKdLFLKCwpo8LSMoGXEQBWzA4MCjswdmIcI+dxjIRMlAziJEfJShUnQxCTGKmiZBAngyhZAxfGqq2H4MCU+zJRcgEDTMVJdmDxXBjHSAUxBS8jREkVJ6NcmI6SrR0mTiqASZxcZBxYOEpaiDG4FlsXpqMkgyzagS3lGAkZgHUzcARiJkpaiLELM1GSY+RyhhccmAhRkoW4nFNQTLOTUrz8Gby2dwC8iiD+IGLkF5dSQfE8UWEJ6wUQs3HSiZLSiek+LF4n5kKskuPkv4OYRElAjDuxkBPTLiyAWBAllRsLoqR1YroPU07s60As6MSsC9NuTDqxLiUVJeNAzETJ50CsJx7E2IXh98I5A1TTZ8/x8mfw2t8BfMYi+BDmFZaI8osghhcUDTF2Y0UQw8xESXFh4sQqVBcW04cFEEOMNMV+BTsxKAZi6MLYjUHVKPVtF6aiZFyIsSurs31Yo4qTL+rDGGKqC3P7MFXsqziJYl+V+rbY5zjZzuV+dB9mILaYz1EkXZhRECURKa0T0xCTLkz3YT2m1Gf7C0eZlplNU6bP8vJn4O+AcwfweYtgypaTX6RUUES5HEHyoEKWhljgxJQbEyfmQExAFoqTTrGvnVhoOqljpTudFJCZYt9OKE2kBMj0dNKZUEqklOmkM5k0xb6U+mpCaSBmezEznXRLfURLAzKeUMZMJ7nUj+nEHIgF08muYDqpIWYmlDGlvplOMsQwJMA5wlH986tpXv4M/B2IcwfAqwgcRXZeAauQsvMLQ/ACwARiAJjrxBwXVqABJhBzIqWCmCn22YkJvPRqhS71g04svGJhnVg1u7GY9QrViyknFrixGh75A2AmStqppI2TmE7qYt91Yk1qxQJRMoiTxoXpYl/WK0ypr1yYdWJmKilOTE0l7WRSSn1d7LMDCxX7uhNDRE5Oy6TPJn/l5c/A34EX3AF87iIoqTNzC0RZLAswAzF2XyiABWAMr1wdJSVSoguLipICMYaX7cQYXEWOCyvmKCnFfjyIOX1YmbMjphyYjpOAWI3pw3SxLzti9VTl7IjZ/TDtwgRiDWZHrIkWxN0RU31YQ7MDsbilfmyUFIhxqd8qaxVuqe/uiKmpJH4Nzmny1Bn0yeeTvfwZ+DvwkncAvIpgGz4jm5cSRfmUmQMFEAPIsgAwLRMlc3WUVE5MdWIGYhInBWam2GeIWSemppRmMhmaTgrMgvWKmOmk9GJqOhnbiTlRshYrFgwxZ0fMTiddiDmLrlLsy4QyznSSy/2QE7NRkkt9p9i3fRj2w0ycdJwYOrw5yen04Sefefkz8Hfga9wB8CqCvictM5fSs7QswPIoExDLzWcHBsGJBfBScVJ3Yfnaidk+zBT7YXhJH8aSQl8gFuyHmU4seioZQIwjpOnCXrDkKvthekcstgtrUEuuug+LXnCVTX13W99GSXZgejIJN2Y39bFiwZJS365XBE4MsMPZfTrpC5r40d+9/Bn4O/AN7gB4FUFsSuFFRSwrpvLEKjUzRyCW5kAsnUEGBU4MMFNxMov7MOvELMRUoR90YuHpZD6DC4p1YnH2xHScFJixC3uuE7Nxkt2YLvSxra+eHbmLrhwlzbMj98mRU+rX2CdHwa6YuDC9KxZ6duQ8ObJ7YgwxuEGU6gDV+xM/8vJn4O/At3AHwKsIntckp2eqJwAZULaFGMbuaQKxHOXEsiEdJfUbL8TJwImZToz/l0t9cWLSiTkQ06V+bLHPcVJKfbcTc9crVKTEekVJuSn2GWKy6KolnViVbOkHk0ls7OtOLM5UEkW4vJmMejcpKxYo9u2yq/NmMuTE9LY+F/o40Ew+l4//MYnemzDRy5+BvwPf8h0AryL40M5NzaBkiKdYIgsx7cDEiSl4CcA0xDIYYrYPky5MSUVJU+yrSJmjpbowd7UiiJKyH+YU+2q1QsdJva3v7ogZiLk7YhZgzqJrADG3DwuK/dBzIwsx9WbS7IfZHTHz6NvpwwDIL7lU//NfPqB3x0/w8mfg78B/6Q6AVxHEGJTDc/gNF5TE8ALERNEQS1cuLIiTOTpOaiemI6WAzHFiNkrKdNIp9QGyGCdmSn216Bosu+pSX/bEzHRSPz2KN52MWnQVmGknJlv77nTSODH34bd9dmTeTepiXy+5AmI4H5Tqv3t3vJc/A38HvoM7AF5FMKFLnJtKiclpDC9WCqQf4jK4FMQy5QMaQMz8VAG3CwuipOnDgqkkSn0WnJgt9cNTSVPqh6aSzmTSbOu7z43MjpjZ1A8X+/xuUvowxEk1lXxeH+ZGSfsjeDTA3FIflMfAYPKU6TTuT+/T2+P+6OXPwN+B7/AOgFcRfKjNI9yEpFRKAMBciAnMDMQcJxYXYllOoR8LsaDQdyDmxklZco1adJVeTC+5xll0VRDTitnUd6eT0RBzQKYfgKt3k7oT072Y2RGD85zwwd/o1++M8/Jn4O/A93QHwKsItthnJc5lJdOsOck0G0qCUigBMhCbq52YdmTyY1FSXxJiejppOrG0rDjFvkRK04kFvVi2iZSyrW829l8SYs6TI7PsGnRibrHvLrvO18V+lbwEmPTlVPrtH96jN956x8ufgb8D3/MdAK8icCkzEpJoZsJcmsnwgiy8BGIaXgIwDTEGVxAndRfGELNdWEypz9NJtwuT9Qqn2LddmC72uQ/DFE7FSV3oR23rG4DZYt+ZSqrJZJyH3xpi6rmRWXLV8HIefuPrf3/ih/TzN3/j5c/A34FX6A6AVxHsUk2flciaQzN4r2hGAgSIsQzEtAszMBMH5jqxZHRiqboTCyDmlvp2MsmxMgWS9QodJ58HMYaZKfUVxFjOZBI7YsGmvnJhuZCZTgrIzLtJF2L64bcDMTxR+vyLKfSrt39PP/7Fm17+DPwdeAXvAHgVwYd+6sxE0TSIATaNAaYglmQVH2L8A+nYicV2YuzE3DjpFPvKjenVCplOMrwgvSMmS64hiAXb+hlZ5rmR3taPKfYdiOWpbf1cd1s/tCOmJpMA8/gJf6Uf/uSXXv4M/B14xe8AeCUb8VOmzxZNncGamWAVDTFseBuQCcQQKVnSiXGkCjoxBTIU+4kQA+xFEHOnkwIx+Znfzp5Y9KIrXNh/ALFsC7EicW8ffzqJfvbGW/SDH/3Uy5+BvwP/I3cAldG/AGqoigILRknJAAAAAElFTkSuQmCCCwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</imageBackground>
            </state>
          </states>
        </style>
        <style role="TimelineViewTimeSlotWorkingHour">
          <states>
            <state name="Normal" backColor="120, 120, 120" backGradientStyle="None" backHatchStyle="None" />
          </states>
        </style>
        <style role="UltraButton" buttonStyle="FlatBorderless" />
        <style role="UltraButtonDefault">
          <states>
            <state name="Normal" borderAlpha="Transparent" />
          </states>
        </style>
        <style role="UltraCalculator">
          <states>
            <state name="Normal" backColor="White" backGradientStyle="None" backHatchStyle="None" />
          </states>
        </style>
        <style role="UltraCalculatorButtonBase">
          <states>
            <state name="Normal" backColor="White" backGradientStyle="None" backHatchStyle="None" />
          </states>
        </style>
        <style role="UltraDropDownButtonMainButton">
          <states>
            <state name="Normal" imageBackgroundStyle="Stretched" imageBackgroundStretchMargins="3, 3, 3, 3">
              <imageBackground>AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAAywAAAAKJUE5HDQoaCgAAAA1JSERSAAAADAAAAAsIBgAAAEtwbF8AAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsMAAALDAE/QCLIAAAANElEQVQoU2Po7Jn6nxTMAFJMLACphWs4c+bMf3wYZCiGBlw2gQwathpICiVi4gIerKTENAC8HcbYRfL06gAAAABJRU5ErkJgggsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=</imageBackground>
            </state>
          </states>
        </style>
        <style role="UltraOptionSet">
          <states>
            <state name="Normal" themedElementAlpha="Opaque" />
          </states>
        </style>
        <style role="UltraProgressBar" borderStyle="Rounded1">
          <states>
            <state name="Normal" borderColor="169, 177, 184" />
          </states>
        </style>
        <style role="UltraTile">
          <states>
            <state name="Normal" backColor="210, 210, 210" imageBackgroundStyle="Stretched" backColor2="White" backGradientStyle="Vertical" imageBackgroundStretchMargins="3, 3, 3, 3">
              <imageBackground>AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj0yLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAAywAAAAKJUE5HDQoaCgAAAA1JSERSAAAADAAAAAsIBgAAAEtwbF8AAAABc1JHQgCuzhzpAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAAsMAAALDAE/QCLIAAAANElEQVQoU2Po7Jn6nxTMAFJMLACphWs4c+bMf3wYZCiGBlw2gQwathpICiVi4gIerKTENAC8HcbYRfL06gAAAABJRU5ErkJgggsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=</imageBackground>
            </state>
          </states>
        </style>
        <style role="UnpinnedTabAreaTop">
          <states>
            <state name="Normal" backColor="208, 212, 221" backGradientStyle="None" backHatchStyle="None" />
          </states>
        </style>
      </styles>
    </styleSet>
    <styleSet name="SpellCheckDialog">
      <styles>
        <style role="UltraLabel">
          <states>
            <state name="Normal" foreColor="68, 68, 68" />
          </states>
        </style>
      </styles>
    </styleSet>
    <styleSet name="SpellCheckDialog_DropShadow">
      <styles>
        <style role="UltraLabel">
          <states>
            <state name="Normal" foreColor="210, 210, 210" />
          </states>
        </style>
      </styles>
    </styleSet>
  </styleSets>
  <resources>
    <resource name="GridCellEditMode" backColor="255, 232, 166" textVAlign="Middle" imageBackgroundStyle="Stretched" backGradientStyle="None" backHatchStyle="None" imageBackgroundStretchMargins="2, 2, 2, 2" />
    <resource name="GridColumnHeaderHotTracked" backColor="Transparent" textVAlign="Middle" backGradientStyle="None" backHatchStyle="None" imageBackgroundStretchMargins="2, 2, 2, 2" />
    <resource name="GridColumnHeaderNormal" backColor="White" foreColor="30, 30, 30" textVAlign="Middle" imageBackgroundStyle="Stretched" backColor2="Gainsboro" backGradientStyle="Vertical" textTrimming="EllipsisCharacter" imageBackgroundStretchMargins="2, 2, 2, 2" />
    <resource name="GridControlAreaNormal" backColor="255, 232, 166" backGradientStyle="None" backHatchStyle="None" />
    <resource name="GridRowActive" backColor="254, 202, 97" textVAlign="Middle" backGradientStyle="None" textTrimming="EllipsisCharacter" backHatchStyle="None" imageBackgroundStretchMargins="2, 2, 2, 2" />
    <resource name="GridRowAlternateItem" backColor="White" backGradientStyle="None" backHatchStyle="None" />
    <resource name="GridRowFilterRow" backColor="212, 238, 251" borderColor="Transparent" textVAlign="Middle" backGradientStyle="None" backHatchStyle="None" />
  </resources>
</styleLibrary>